--------------------------------------------------------
--  File created - Monday-February-09-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View WL_APPROVED_PROFILES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "&1"."WL_APPROVED_PROFILES" ("PROFILE_ID", "RULE_ID") AS 
  SELECT P.PROFILE_ID,
    R.RULE_ID
  FROM WL_PROFILES P,
    wl_rules r
  WHERE NVL(LOWER(P.AUTHENTICATED_IDENTITY),'NULL') LIKE NVL(LOWER(R.AUTHENTICATED_IDENTITY),'NULL') AND
  NVL(LOWER(P.ENTERPRISE_IDENTITY),'NULL') LIKE NVL(LOWER(R.ENTERPRISE_IDENTITY),'NULL') AND
  NVL(LOWER(P.GLOBAL_UID),'NULL') LIKE NVL(LOWER(R.GLOBAL_UID),'NULL') AND
  NVL(LOWER(P.OS_USER),'NULL') LIKE NVL(LOWER(R.OS_USER),'NULL') AND
  NVL(LOWER(P.PROXY_ENTERPRISE_IDENTITY),'NULL') LIKE NVL(LOWER(R.PROXY_ENTERPRISE_IDENTITY),'NULL') AND
  NVL(LOWER(P.PROXY_USER),'NULL') LIKE NVL(LOWER(R.PROXY_USER),'NULL') AND
  NVL(LOWER(P.PROXY_USERID),'NULL') LIKE NVL(LOWER(R.PROXY_USERID),'NULL') AND
  NVL(LOWER(P.SESSION_USER),'NULL') LIKE NVL(LOWER(R.SESSION_USER),'NULL') AND
  NVL(LOWER(P.SESSION_USERID),'NULL') LIKE NVL(LOWER(R.SESSION_USERID),'NULL') AND
  NVL(LOWER(P.AUTHENTICATION_DATA),'NULL') LIKE NVL(LOWER(R.AUTHENTICATION_DATA),'NULL') AND
  NVL(LOWER(P.AUTHENTICATION_METHOD),'NULL') LIKE NVL(LOWER(R.AUTHENTICATION_METHOD),'NULL') AND
  NVL(LOWER(P.BG_JOB_ID),'NULL') LIKE NVL(LOWER(R.BG_JOB_ID),'NULL') AND
  NVL(LOWER(P.CLIENT_IDENTIFIER),'NULL') LIKE NVL(LOWER(R.CLIENT_IDENTIFIER),'NULL') AND
  NVL(LOWER(P.CLIENT_INFO),'NULL') LIKE NVL(LOWER(R.CLIENT_INFO),'NULL') AND
  NVL(LOWER(P.DBLINK_INFO),'NULL') LIKE NVL(LOWER(R.DBLINK_INFO),'NULL') AND
  NVL(LOWER(P.FG_JOB_ID),'NULL') LIKE NVL(LOWER(R.FG_JOB_ID),'NULL') AND
  NVL(LOWER(P.HOST),'NULL') LIKE NVL(LOWER(R.HOST),'NULL') AND
  NVL(LOWER(P.IDENTIFICATION_TYPE),'NULL') LIKE NVL(LOWER(R.IDENTIFICATION_TYPE),'NULL') AND
  NVL(LOWER(P.IP_ADDRESS),'NULL') LIKE NVL(LOWER(R.IP_ADDRESS),'NULL') AND
  NVL(LOWER(P.ISDBA),'NULL') LIKE NVL(LOWER(R.ISDBA),'NULL') AND
  NVL(LOWER(P.LANGUAGE),'NULL') LIKE NVL(LOWER(R.LANGUAGE),'NULL') AND
  NVL(LOWER(P.MODULE),'NULL') LIKE NVL(LOWER(R.MODULE),'NULL') AND
  NVL(LOWER(P.NETWORK_PROTOCOL),'NULL') LIKE NVL(LOWER(R.NETWORK_PROTOCOL),'NULL') AND
  NVL(LOWER(P.SERVICE_NAME),'NULL') LIKE NVL(LOWER(R.SERVICE_NAME),'NULL') AND
  NVL(LOWER(P.TERMINAL),'NULL') LIKE NVL(LOWER(R.TERMINAL),'NULL') AND
  NVL(LOWER(P.DATABASE_ROLE),'NULL') LIKE NVL(LOWER(R.DATABASE_ROLE),'NULL') AND
  NVL(LOWER(P.DB_DOMAIN),'NULL') LIKE NVL(LOWER(R.DB_DOMAIN),'NULL') AND
  NVL(LOWER(P.DB_NAME),'NULL') LIKE NVL(LOWER(R.DB_NAME),'NULL') AND
  NVL(LOWER(P.DB_UNIQUE_NAME),'NULL') LIKE NVL(LOWER(R.DB_UNIQUE_NAME),'NULL') AND
  NVL(LOWER(P.INSTANCE),'NULL') LIKE NVL(LOWER(R.INSTANCE),'NULL') AND
  NVL(LOWER(P.INSTANCE_NAME),'NULL') LIKE NVL(LOWER(R.INSTANCE_NAME),'NULL') AND
  NVL(LOWER(P.NLS_CALENDAR),'NULL') LIKE NVL(LOWER(R.NLS_CALENDAR),'NULL') AND
  NVL(LOWER(P.NLS_CURRENCY),'NULL') LIKE NVL(LOWER(R.NLS_CURRENCY),'NULL') AND
  NVL(LOWER(P.NLS_DATE_FORMAT),'NULL') LIKE NVL(LOWER(R.NLS_DATE_FORMAT),'NULL') AND
  NVL(LOWER(P.NLS_SORT),'NULL') LIKE NVL(LOWER(R.NLS_SORT),'NULL') AND
  NVL(LOWER(P.NLS_TERRITORY),'NULL') LIKE NVL(LOWER(R.NLS_TERRITORY),'NULL') AND
  NVL(LOWER(P.SERVER_HOST),'NULL') LIKE NVL(LOWER(R.SERVER_HOST),'NULL') AND
  NVL(LOWER(P.SESSION_EDITION_ID),'NULL') LIKE NVL(LOWER(R.SESSION_EDITION_ID),'NULL') AND
  nvl(lower(p.session_edition_name),'NULL') like nvl(lower(r.session_edition_name),'NULL');
