--------------------------------------------------------
--  File created - Monday-February-09-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WL_PROFILES
--------------------------------------------------------

  CREATE TABLE "&1"."WL_PROFILES" 
   (	"PROFILE_ID" NUMBER, 
	"LAST_USED_DATE" DATE, 
	"AUTHENTICATED_IDENTITY" VARCHAR2(256 CHAR), 
	"ENTERPRISE_IDENTITY" VARCHAR2(256 CHAR), 
	"GLOBAL_UID" VARCHAR2(256 CHAR), 
	"OS_USER" VARCHAR2(256 CHAR), 
	"PROXY_ENTERPRISE_IDENTITY" VARCHAR2(256 CHAR), 
	"PROXY_USER" VARCHAR2(256 CHAR), 
	"PROXY_USERID" VARCHAR2(256 CHAR), 
	"SESSION_USER" VARCHAR2(256 CHAR), 
	"SESSION_USERID" VARCHAR2(256 CHAR), 
	"AUTHENTICATION_DATA" VARCHAR2(256 CHAR), 
	"AUTHENTICATION_METHOD" VARCHAR2(10 CHAR), 
	"BG_JOB_ID" VARCHAR2(10 CHAR), 
	"CLIENT_IDENTIFIER" VARCHAR2(256 CHAR), 
	"CLIENT_INFO" VARCHAR2(256 CHAR), 
	"DBLINK_INFO" VARCHAR2(256 CHAR), 
	"FG_JOB_ID" VARCHAR2(10 CHAR), 
	"HOST" VARCHAR2(256 CHAR), 
	"IDENTIFICATION_TYPE" VARCHAR2(20 CHAR), 
	"IP_ADDRESS" VARCHAR2(20 CHAR), 
	"ISDBA" VARCHAR2(5 CHAR), 
	"LANGUAGE" VARCHAR2(256 CHAR), 
	"MODULE" VARCHAR2(256 CHAR), 
	"NETWORK_PROTOCOL" VARCHAR2(10 CHAR), 
	"SERVICE_NAME" VARCHAR2(256 CHAR), 
	"TERMINAL" VARCHAR2(256 CHAR), 
	"DATABASE_ROLE" VARCHAR2(256 CHAR), 
	"DB_DOMAIN" VARCHAR2(256 CHAR), 
	"DB_NAME" VARCHAR2(256 CHAR), 
	"DB_UNIQUE_NAME" VARCHAR2(256 CHAR), 
	"INSTANCE" VARCHAR2(256 CHAR), 
	"INSTANCE_NAME" VARCHAR2(256 CHAR), 
	"NLS_CALENDAR" VARCHAR2(256 CHAR), 
	"NLS_CURRENCY" VARCHAR2(256 CHAR), 
	"NLS_DATE_FORMAT" VARCHAR2(256 CHAR), 
	"NLS_SORT" VARCHAR2(256 CHAR), 
	"NLS_TERRITORY" VARCHAR2(256 CHAR), 
	"SERVER_HOST" VARCHAR2(256 CHAR), 
	"SESSION_EDITION_ID" VARCHAR2(256 CHAR), 
	"SESSION_EDITION_NAME" VARCHAR2(256 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL KEEP FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "&2" ;
--------------------------------------------------------
--  DDL for Index WL_PROFILES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "&1"."WL_PROFILES_PK" ON "&1"."WL_PROFILES" ("PROFILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "&2" ;
--------------------------------------------------------
--  Constraints for Table WL_PROFILES
--------------------------------------------------------

  ALTER TABLE "&1"."WL_PROFILES" ADD CONSTRAINT "WL_PROFILES_PK" PRIMARY KEY ("PROFILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "&2"  ENABLE;
  ALTER TABLE "&1"."WL_PROFILES" MODIFY ("LAST_USED_DATE" NOT NULL ENABLE);
  ALTER TABLE "&1"."WL_PROFILES" MODIFY ("PROFILE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger WL_PROFILES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "&1"."WL_PROFILES_TRG" 
BEFORE INSERT ON "&1".WL_PROFILES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PROFILE_ID IS NULL THEN
      SELECT WL_PROFILES_SEQ.NEXTVAL INTO :NEW.PROFILE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "&1"."WL_PROFILES_TRG" ENABLE;
