CREATE SMALLFILE TABLESPACE &1     
DATAFILE SIZE 102400 K AUTOEXTEND ON NEXT 102400 K MAXSIZE UNLIMITED     
LOGGING     
ONLINE     
PERMANENT     
DEFAULT NOCOMPRESS     
EXTENT MANAGEMENT LOCAL AUTOALLOCATE     
FLASHBACK ON;