CREATE USER &1
IDENTIFIED BY VALUES 'no_login_allowed'
DEFAULT TABLESPACE &2
QUOTA UNLIMITED ON &2
PROFILE DEFAULT
ACCOUNT UNLOCK;

GRANT CREATE INDEXTYPE,
      CREATE VIEW,
      CREATE CLUSTER,
      CREATE SESSION,
      CREATE JOB,
      CREATE MATERIALIZED VIEW,
      CREATE TRIGGER,
      CREATE SYNONYM,
      CREATE ANY CONTEXT,
      CREATE OPERATOR,
      CREATE SEQUENCE,
      CREATE TABLE,
      CREATE DIMENSION,
      CREATE TYPE,
      CREATE PROCEDURE
   TO &1;